site_name: audian

repo_url: https://github.com/bendalab/audian/

edit_uri: ""

site_author: Benda-Lab

theme: readthedocs
    
nav:
    - Home: 'index.md'
    - User manual: 'usermanual/index.html'
    - API reference: 'api/index.html'
